### ISSUE TITLE
Not able to load the neuron model more than once in seperate python processes. 

### ISSUE THREAD

**Issue by dingusagar** [aws-neuron/aws-neuron-sdk#453]
I was using gunicorn + fastapi to build an inference app in the AWS inferentia box. 
A model is compiled to the neuron format and I was able to start the python app like this. 

` gunicorn main:app --workers 1  --bind 0.0.0.0:8000  --worker-class uvicorn.workers.UvicornWorker `

This was working perfectly fine. 
But the moment I tried to increase the number of workers, the application failed to start up with the following error. 
` gunicorn main:app --workers 2  --bind 0.0.0.0:8000  --worker-class uvicorn.workers.UvicornWorker `

```
2022-Jul-21 11:15:58.0121 21628:21628 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:4 Available:0
[2022-07-21 11:15:58 +0000] [21628] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dingusagar/convnext_base_in22k_neuron/main.py", line 21, in <module>
    model_neuron = torch.jit.load('assets/convnext_base_in22k_neuron.pt')
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/dingusagar/pytorch_venv/lib64/python3.7/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged
to your system logs. See the Neuron Runtime's troubleshooting guide for help on this
topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/
[2022-07-21 11:15:58 +0000] [21628] [INFO] Worker exiting (pid: 21628)
[2022-07-21 11:15:59 +0000] [21618] [WARNING] Worker with pid 21627 was terminated due to signal 15
[2022-07-21 11:15:59 +0000] [21618] [INFO] Shutting down: Master
[2022-07-21 11:15:59 +0000] [21618] [INFO] Reason: Worker failed to boot.
```

Then I noticed that if you two python processes are trying to load the same model like this, It gives the same error. 
```py
model_neuron = torch.jit.load('assets/neuron_compiled_model.pt')
```
How can I increase the parallelism of my inference app? What is the recommended approach?

**Comment by dingusagar** [comment]
This got solved by adding the following lines to the scirpt.
```py
import os

os.environ['NEURON_RT_NUM_CORES']='2'
```
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/appnotes/perf/parallel-ncgs.html

**Comment by indianfungus** [comment]
Hey, sorry to comment on this but, I am running into the same error. 

I too have converted my model from pytorch to run on inferentia and get the error that there are not enough neuron cores available.

Something like this:
```
2022-Aug-16 01:26:56.0709 25009:25009 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:16 Available:0
```

I tried out your solution above but, that does not work for me. 

Any other things that may work?

**Comment by dingusagar** [comment]
Hi @indianfungus ,
Could u check if you installed the AWS neuron tools properly. https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/pytorch-setup/pytorch-install.html

You can use the neuron-top command to see the neuron cores available.

**Comment by indianfungus** [comment]
Hey @dingusagar, thanks for the quick reply!

I use `neuron-top` and I can see that there are neuron cores available which are not being used. 

![Uploading Screen Shot 2022-08-16 at 9.06.55 AM.png…]()

As can be seen in the image above, only 1 core is being used with a single worker. 

As soon as I add in more than 1 worker, I see the CPU usage spike up but, there are no models which are loaded as the process crashes.

**Comment by indianfungus** [comment]
Actually @dingusagar , I got multiple models loaded!

I did this by setting:

```
import os

os.environ['NEURON_RT_NUM_CORES']='1'
```

I assume this tells each process that they have access to a single core and can use that core only.

**Comment by aws-taylor** [comment]
Hello @indianfungus,

  You are correct. Take a look at https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-runtime/nrt-configurable-parameters.html for documentation on which environment variables are available. In particular, you may find `NEURON_RT_VISIBLE_CORES` useful as a way to bind specific cores to specific workers.
  
  -Taylor

**Comment by dingusagar** [comment]
hi @indianfungus ,
Ok, I think I ran into the same problem. 
Can you try increasing the environment variable from 1 to a higher number. 
If that doesn't work, try adding --preload option in gunicorn command. 
I am not exactly sure how this environment variable and gunicorns forking of worker processes work together, but I was playing around with the above methods and it started working. 

I am reopening this issue so that someone else from the community might be able to give more insights.

**Comment by awsrjh** [comment]
Hi @dingusagar and @indianfungus : did @aws-taylor 's suggestion help?

**Comment by dingusagar** [comment]
hi @awsrjh, the issue I faced is resolved.

**Comment by awsrjh** [comment]
excellent - will close. thanks!
